This PR completes Mess Section
iraapp/ira pull request #42
Opened 2022-09-10 13:17 UTC by mtabishk

Adds following changes:
- Mess Menu Student UI and API Integration
- Mess Menu Manager UI and API Integration
- Mess Complaint and API Integration
- Updated MOM and Tenders UI

2022-09-10 13:47 UTC, ashutoshc8101 requested changes

2022-09-10 13:47 UTC, ashutoshc8101 commented on app/.gitignore
> +upload-keystore.jks
Revert this change

2022-09-10 13:47 UTC, ashutoshc8101 commented on app/android/app/build.gradle
> +            keyPassword 'password'
Revert these changes.

2022-09-10 13:47 UTC, ashutoshc8101 commented
@Jeetu303 Please review the video.

2022-09-10 14:22 UTC, mtabishk commented on app/.gitignore
> +upload-keystore.jks
Done

2022-09-10 14:22 UTC, mtabishk commented on app/android/app/build.gradle
> +            keyPassword 'password'
Done

2022-09-10 14:24 UTC, mtabishk commented
@ashutoshc8101 Changes done

2022-09-10 14:32 UTC, ashutoshc8101 approved these changes

2022-09-10 16:00 UTC, Jeetu303 commented
All this looks good in both videos. 
When you add an item or change the time of a meal and update it and go to the student's side, an update should get reflected there also. Show this process in one video... Do not add or change via Django administration... Login manager side, do changes then login as a student... @ashutoshc8101 @mtabishk

2022-09-10 16:01 UTC, Jeetu303 commented
Mess Complaint and API Integration
Updated MOM and Tenders UI
I cannot see videos for the above ones @mtabishk @ashutoshc8101

2022-09-13 16:59 UTC, Jeetu303 commented
@mtabishk @ashutoshc8101 do this please

2022-09-13 20:27 UTC, ashutoshc8101 commented
@mtabishk Flutter analyze is failing.

2022-09-14 06:47 UTC, mtabishk commented
@ashutoshc8101 
![flutter analyze](https://user-images.githubusercontent.com/61789893/190080414-af145fbb-3cf0-418f-a7f0-8fab5d0acb85.png)

Its not failing on my end

2022-09-16 17:58 UTC, Jeetu303 commented
When the manager log-ins it should show all the functionalities ... But shows Mess.... This page is for mess managers... it should directly go to functionalities. Remove that page(video time 1:02 around)...
If the mess manager can edit timing, then everything is fine. 
@mtabishk Do these two things when done merge pr @ashutoshc8101 
Good job keep it up

2022-09-17 07:10 UTC, mtabishk commented
@Jeetu303 @ashutoshc8101 
Made the suggested changes 

https://user-images.githubusercontent.com/61789893/190845143-41d7a3eb-afee-4587-8379-8b7807377148.mp4

2022-09-17 07:43 UTC, Jeetu303 commented
Quoting the last comment again "**If the mess manager can edit timing, then everything is fine.** 
So read comment carefully ... @ashutoshc8101 @mtabishk if that is happening then go ahead and merge if not then do that first then merge

2022-09-17 07:53 UTC, mtabishk commented
@ashutoshc8101 Fixed merge conflicts

2022-09-17 07:59 UTC, mtabishk commented
@ashutoshc8101 
Mess Timings video

https://user-images.githubusercontent.com/61789893/190846852-f4fe03a9-8b15-4755-9bd1-e6f11cffb833.mp4

2022-09-17 08:19 UTC, merged